name: mists
version: 0.04.0
author: Du≈°an Kasan <dusan@kasan.sk>
description: A simple and modular web server
homepage: https://github.com/DusanKasan/Mist
documentation: https://github.com/DusanKasan/Mist
dependencies:
  mock: '>=0.11.0+1 <0.12.0'
  unittest: '>=0.11.0+1 <0.12.0'
